export const VISION_MODELS = [
  {
    id: "google/gemini-2.0-flash-001",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    providerColor: "#4285f4",
    desc: "เร็ว ราคาถูก OCR แม่นยำ ภาษาไทยดีมาก",
    badge: "แนะนำ",
    badgeColor: "#f0c040",
  },
  {
    id: "google/gemini-2.5-pro-preview-06-05",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    providerColor: "#4285f4",
    desc: "คุณภาพสูงสุด วิเคราะห์ภาพซับซ้อน เอกสารยาก",
    badge: "Pro",
    badgeColor: "#a78bfa",
  },
  {
    id: "anthropic/claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    providerColor: "#d97706",
    desc: "อ่านสลิปธนาคารไทยและใบเสร็จได้ดีเยี่ยม",
    badge: null,
    badgeColor: null,
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    providerColor: "#10b981",
    desc: "OCR แม่นยำ รองรับหลายภาษา เชื่อถือได้",
    badge: null,
    badgeColor: null,
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    providerColor: "#10b981",
    desc: "ราคาถูก เร็ว เหมาะงานสแกนรูปทั่วไป",
    badge: "ประหยัด",
    badgeColor: "#34d399",
  },
  {
    id: "qwen/qwen2.5-vl-72b-instruct",
    name: "Qwen2.5 VL 72B",
    provider: "Alibaba",
    providerColor: "#f87171",
    desc: "OCR ภาษาไทย จีน ญี่ปุ่น แม่นยำมาก",
    badge: null,
    badgeColor: null,
  },
  {
    id: "google/gemma-4-26b-a4b-it",
    name: "Gemma 4 26B",
    provider: "Google",
    providerColor: "#4285f4",
    desc: "Gemma รุ่นใหม่ เร็ว น้ำหนักเบา รองรับ vision",
    badge: "ใหม่",
    badgeColor: "#60a5fa",
  },
  {
    id: "meta-llama/llama-3.2-11b-vision-instruct:free",
    name: "Llama 3.2 Vision 11B",
    provider: "Meta",
    providerColor: "#60a5fa",
    desc: "ฟรี! เหมาะทดสอบ ความแม่นอาจน้อยกว่า",
    badge: "ฟรี",
    badgeColor: "#34d399",
  },
];

export const DEFAULT_MODEL = VISION_MODELS[0].id;
